# Generated by Django 4.0 on 2022-02-23 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('code', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('last_trade_date', models.IntegerField(default=0)),
                ('tse_id', models.CharField(max_length=20)),
                ('isin', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('en_symbol', models.CharField(default='', max_length=20)),
                ('en_symbol_18', models.CharField(default='', max_length=25)),
                ('en_code_5', models.CharField(default='', max_length=10)),
                ('name', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=64)),
                ('fa_symbol_30', models.CharField(default='', max_length=35)),
                ('cisin', models.CharField(default='', max_length=18)),
                ('nominal_val', models.FloatField(default=0, max_length=18)),
                ('stock_qnt', models.FloatField(default=0, max_length=18)),
                ('change_date', models.IntegerField(default=0)),
                ('change_type', models.IntegerField(default=0)),
                ('shit_type_AIO', models.CharField(default='', max_length=5)),
                ('group_code', models.CharField(default='', max_length=5)),
                ('initial_date', models.IntegerField(default=0)),
                ('unit', models.IntegerField(default=0)),
                ('market_code', models.CharField(default='', max_length=10)),
                ('board_code', models.CharField(default='', max_length=10)),
                ('ind_code', models.CharField(default='', max_length=10)),
                ('sub_ind_code', models.CharField(default='', max_length=10)),
                ('clear_delay', models.IntegerField(default=0)),
                ('min_allowed_price', models.FloatField(default=0, max_length=10)),
                ('max_allowed_price', models.FloatField(default=0, max_length=10)),
                ('base_vol', models.CharField(default='', max_length=20)),
                ('tick_size', models.PositiveSmallIntegerField(default=1)),
                ('trans_min_size', models.CharField(default='', max_length=20)),
                ('flow', models.IntegerField(default=0)),
                ('order_min_size', models.CharField(default='', max_length=20)),
                ('order_max_size', models.CharField(default='', max_length=20)),
                ('valid', models.BooleanField(default=False)),
                ('market_status', models.CharField(choices=[('NOT_PROVIDED', 'NOT_PROVIDED'), ('ALLOWED', 'ALLOWED'), ('ALLOWED_FROZEN', 'ALLOWED_FROZEN'), ('ALLOWED_SUSPENDED', 'ALLOWED_SUSPENDED'), ('ALLOWED_RESERVED', 'ALLOWED_RESERVED'), ('FORBIDDEN', 'FORBIDDEN'), ('FORBIDDEN_FROZEN', 'FORBIDDEN_FROZEN'), ('FORBIDDEN_SUSPENDED', 'FORBIDDEN_SUSPENDED'), ('FORBIDDEN_RESERVED', 'FORBIDDEN_RESERVED')], default='NOT_PROVIDED', max_length=20)),
                ('rahavard_id', models.CharField(default='0', max_length=20)),
                ('tick_needed', models.BooleanField(default=False)),
                ('tadbir_id', models.CharField(default='', max_length=20)),
                ('type', models.ForeignKey(db_column='code', default=0, on_delete=django.db.models.deletion.CASCADE, to='oracle.instrumenttype')),
            ],
        ),
    ]
