# Generated by Django 4.0 on 2022-02-26 09:18

from django.db import migrations
from django.core.management import call_command

fixtures = ["instrumenttype"]


def load_fixture(apps, schema_editor):
    for fixture in fixtures:
        call_command("loaddata", fixture, app_label="oracle")


class Migration(migrations.Migration):
    dependencies = [
        ('oracle', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
