# Generated by Django 4.0 on 2022-07-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle', '0002_triggerparameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggerparameter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='triggerparameter',
            name='name_en',
        ),
        migrations.AddField(
            model_name='triggerparameter',
            name='name',
            field=models.CharField(default='ROW', max_length=3, primary_key=True, serialize=False, verbose_name='Parameter Name'),
            preserve_default=False,
        ),
    ]
