# Generated by Django 4.0 on 2022-09-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle', '0003_remove_triggerparameter_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Parameter Name')),
                ('name_fa', models.CharField(max_length=128, verbose_name='Persian Name')),
                ('source_type', models.CharField(choices=[('SOCKET', 'Socket'), ('SERVICE', 'Service')], max_length=10)),
            ],
        ),
    ]
